# automatically generated by the FlatBuffers compiler, do not modify

# namespace: exemplo

import flatbuffers

class Ack(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsAck(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Ack()
        x.Init(buf, n + offset)
        return x

    # Ack
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Ack
    def Opcode(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # Ack
    def Block(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def AckStart(builder): builder.StartObject(2)
def AckAddOpcode(builder, opcode): builder.PrependInt32Slot(0, opcode, 0)
def AckAddBlock(builder, block): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(block), 0)
def AckEnd(builder): return builder.EndObject()
